server {
    listen 86;
    client_max_body_size 20M;
        
    location / {
        root /var/www/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /app {
        root /var/www/html;
        index index.html;
        try_files $uri $uri/ index.html;
    }
}

#gzip config start
gzip on;
gzip_disable "msie6";
gzip_min_length 10240;
gzip_buffers 32 32k;
gzip_comp_level 9;
gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
gzip_vary on;
# gzip config end